name: server-integration-test
on: [pull_request]
jobs:
  get-ping-endpoint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17.8'
      - run: go run cmd/test/main.go


